aws-samples/aws-genai-llm-chatbot

- lib/rag-sources/aurora-pgvector/index.ts
Compile time error as the databaseSetupFunction needs architecture
*Description of changes:* Modified method to add the architecture for databaseSetupFunction lambda
> Architecture was missing for createVectorDB method

- lib/model-interfaces/langchain/functions/request-handler/adapters/base/base.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/ai21_j2.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/claude.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/titan.py
#55 
RAG uses langchain `ConversationalRetrievalChain` and with this change we allow to override the 2 prompts used by this chain this fixes the issue with the specific Claude formatting but also allows for further prompt tuning if necessary
> feat: possibility to override the Retrieve prompts

- lib/shared/utils.ts
**Issue:** #70 
**Title:** Update `getName` Function to Adhere to Naming Requirements
Updated the `getName` function in `utils.ts` to ensure generated names adhere to the new naming requirements.
1. Converted the generated name to lowercase.
2. Removed any characters that are not a-z, 0-9, or hyphen.
3. Trimmed hyphens from the start and end of the name.
4. Ensured the name's length is between 3 and 28 characters.
5. Checked that the name starts with a lowercase letter.
6. Added error handling to provide clear feedback if the generated name doesn't meet the requirements.
The changes were made to comply with the naming requirements for AWS resources, ensuring that our infrastructure deployments do not encounter naming-related errors.
Tested on local build with completion success at 9:50am …
> Updated 'getName' naming pattern requirements

- lib/user-interface/react-app/src/components/chatbot/config-dialog.tsx
Fix #113
Set the `step` value to `0.1`
> fix: correct step increment for top p value

- lib/rag-engines/index.ts
- lib/sagemaker-model/deploy-custom-script-model.ts
- lib/sagemaker-model/hf-custom-script-model/index.ts
Fix #122 
Nested CDK constructs names get concatenated and if no resource name is specified in the construct the CDK construct name is used. This might cause some resource identifiers, such as ARNs to exceed the allowed length. 
This fix reduces the length of few known resources.
> Fix too long resource name

- README.md
Fix broken link to Sagemaker quotas in AWS Console
Link to console was not absolute.
Added protocol to console link
> Fix broken link to AWS Console

- lib/model-interfaces/langchain/functions/request-handler/adapters/base/base.py
- lib/user-interface/index.ts
Addressing #155 
* fix use same llm but with streaming forcefully disabled to avoid to streaming back to clients tokens for condense questions.
> Fix condense streaming

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/claude.py
Issue #194 
Changed Claude `get_condense_question_prompt` to make the condensed question generated in the same language as the user input.
> Fixed Claudev2 condensed question to be in the same language as the user input

- lib/shared/file-import-batch-job/requirements.txt
- Bump langchain version for file import jobs to `0.0.331`
> Bump langchain version batch to 0.0.331

- lib/shared/layers/python-sdk/python/genai_core/aurora/query.py
- lib/shared/layers/python-sdk/python/genai_core/opensearch/query.py
Fills up the documents returned by the retriever with the top scored semantic search documents
Fix #197
The fill-up logic is changed so:
- only selects records that have a semantic search score and ignore other records
- for aurora takes into consideration that "inner" metric produces negative values
- correctly implements the filtering of the top-k items
> fix(reranking): uses semantic search score

- .github/workflows/deploy.yml
- .gitignore
- docs/.vitepress/config.mts
- docs/index.md
- package-lock.json
- package.json
#117 
Create skeleton VitePress documentation website with a GitHub action to handle automatic build and deployment to GitHub pages on pushes to the main branch.
> docs: set up VitePress for documentation site hosted on GitHub pages

- lib/shared/index.ts
- lib/shared/shared-asset-bundler.ts
fix #216
Introduced a custom hash function to calculate the md5 hash of all source files that make up the asset.
> fix(shared_asset): correctly calculate hash to detect changes

- lib/shared/index.ts
Setting POWERTOOLS_DEV variable default to "false" to get more compact logging
> fix(powertools): set dev env var to false for compact logging

- cli/magic-create.ts
This is an effort to improve the user experience by providing clearer and emphasized instructions on how to use the multiselect option in the configuration creation tool.
NOTE: blue highlight is just to show the difference
> fix(create_tool): better hints on multiselect

- lib/shared/layers/python-sdk/python/genai_core/clients.py
fix #246 
Removes the use of the Bedrock endpoint configuration so that the code always uses the default regional endpoint. 
> fix(bedrock_endpoint): removing the use of the bedrock endpoint

- lib/shared/file-import-batch-job/requirements.txt
There is no issue available.
* Adding `feedparser==6.0.10` to the list of requirements for a task.
* It fixes the following error: `ModuleNotFoundError: No module named 'feedparser'`
* It happens when processing files for workspaces in the ECS docker image
> Fix error with module not found for feedparser

- lib/shared/layers/python-sdk/python/genai_core/models.py
Bedrock can return FMs that are not valid, such as `foundation-model/amazon.dummy-model`
Currently, when calling list models in boto3 for bedrock, there is an exception caused if the list of models returns invalid models. 
An example of a bad model in the list of models:
`{'modelArn': 'arn:aws:bedrock:us-west-2::foundation-model/amazon.dummy-model', 'modelId': 'amazon.dummy-model', 'inferenceTypesSupported': ['ON_DEMAND']
}`
Since this model has no `inputModalities` or `outputModalities` it raises an exception and returns no models back. 
This change adds checks for `inputModalities` and `outputModalities` being present in the model details and skips the model if it's invalid. 
This change has been applied to both the `list_bedrock_finetuned_models` & …
> fix(genai_core): Added handling for bad FMs

- lib/shared/layers/common/requirements.txt
- lib/shared/layers/python-sdk/python/genai_core/models.py
- lib/shared/layers/python-sdk/python/genai_core/types.py
resolves: #267 
Only retrieve ON_DEMAND inference models that support TEXT output when listing foundation models, and filters out those that are not marked as ACTIVE. For this to work `boto3` was updated to latest version.
> Feature: filter out Bedrock models that cannot be used in the playground

- lib/shared/layers/python-sdk/python/genai_core/websites/crawler.py
fix issue #209 
Added a check on the `"Content-Type"` of the returned page and only process `"text/html"`
> fix(crawler): only process "text/html" Content-Type pages

- lib/rag-engines/opensearch-vector/index.ts
VPC endpoint creation for open search fails if subnets are in the same availabilty zone. 
Check if selected subnets have different availability zones.
> vpc endpoint subnets should be in different availability zones

- lib/rag-engines/opensearch-vector/index.ts
Minor change to update the id of the `CreateOpenSearchWorkspace` construct created in the `rag-engines/opensearch-vector` Opensearch vector store.
> fix(opensearch-vector): updates the name of the Workspace/workflow for the OpenSearcherveless sample

- lib/shared/layers/python-sdk/python/genai_core/sessions.py
*Issue #289:* For the users who have long conversation histories and a lot of items in sessions table, all the records were not displayed on the UI.
*Description of changes:* DynamoDB query operation was not returning all the records because the total size of records was more than 1MB and in such cases, DynamoDB query operation does not handle pagination automatically.
As a fix, added code to handle the pagination based on the 'LastEvaluatedKey' returned by DynamoDB.
> All the sessions are not displayed in the history

- lib/rag-engines/opensearch-vector/index.ts
*Issue #, if available:* #296
*Description of changes:* Use selectSubnets() instead of filter to ensure only one subnet per AZ. The previous implementation (see #257) seems to have broken the build.
> Use selectSubnets() instead of filter to ensure only one subnet per AZ

- cli/magic-create.ts
- lib/rag-engines/kendra-retrieval/index.ts
- lib/shared/types.ts
Issue #, if available:
https://github.com/aws-samples/aws-genai-llm-chatbot/issues/300
Description of changes:
Allows customers to select their edition of Kendra upfront. Having the option upfront is important because it can be a large and cumbersome process to change from the Developer to Enterprise Edition.
> added setup CLI option for Kendra Enterprise

- docs/index.md
Fix broken link on VitePress docs homepage (link: https://aws-samples.github.io/aws-genai-llm-chatbot/)
> fix: update broken links on docs homepage

- cli/magic-create.ts
- lib/shared/types.ts
During the installer when selecting sagemaker models, annotated the model names with [] denoting the instance type deployed, this helps inform users about the different model options associated efficiencies and allows them to look up costs that are relevant.
Some other small formatting changes.
> feat: installer display instance size used next to model name for sagemaker

- package-lock.json
- package.json
After Vite upgrade as part of security improvements, new dependency @rollup/rollup-linux-x64-gnu is required as optional. This fixes the failed docs:build GitHub action
> fix: include optional dependency to fix missing module on docs build GitHub action

- lib/shared/layers/python-sdk/python/genai_core/websites/crawler.py
I have a website that returns the following header:
'Content-Type': 'text/html; charset=utf-8'
> crawler fails on content-type

- README.md
The link to the VitePress docs site in the README is not very visible to users. This PR changes the link to a button for better visibility. 
Button appearance: https://github.com/dairiley/aws-genai-llm-chatbot/blob/convert_docs_link_to_button/README.md
> docs: change docs link to button to make it clearer to users

- bin/config.ts
- cli/magic-create.ts
- docs/.vitepress/config.mts
- docs/documentation/private-chatbot.md
- docs/guide/deploy.md
- lib/aws-genai-llm-chatbot-stack.ts
- lib/chatbot-api/appsync-ws.ts
- lib/chatbot-api/index.ts
- lib/shared/index.ts
- lib/shared/types.ts
- lib/user-interface/index.ts
- lib/user-interface/private-website.ts
- lib/user-interface/public-website.ts
- lib/user-interface/react-app/src/app.tsx
- lib/user-interface/react-app/src/components/app-configured.tsx
https://github.com/aws-samples/aws-genai-llm-chatbot/issues/309
Allows the deployment of a private website, appsync and backend via the 'npm run create' CLI setup.
A customer needs an [AWS Private CA issued ACM certificate](https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-private.html) available in their AWS account for their chosen domain.
- Use an internal only accessible website (i.e. not Cloudfront)
- Appsync APIs and Web sockets private/only accessible within VPC
- Use VPC endpoints for services
- Use of a AWS Private CA certifice
- Use of a custom domain name
Note: I am not sure if replacing BrowserRouter with HashRouter in `/lib/user-interface/react-app/src/app.tsx` is the best. How would you recommend approaching …
>  Feat: Option to lock down website and infrastructure to VPC/Intranet

- cli/magic-create.ts
When using `npm run create` to configure the chatbot features it is easy to miss selecting a RAG engine. 
Added a validation that at least one engine has been selected if the user answers Yes to the use of RAG.
> Add validation that at least one engine has been selected

- cli/magic-create.ts
- lib/chatbot-api/functions/resolvers/subscribe-resolver.js
- lib/user-interface/react-app/src/components/chatbot/multi-chat.tsx
- lib/user-interface/react-app/src/components/chatbot/utils.ts
Fixes #341
Added `sessionId` to the GraphQL advanced subscription filter.
Without advanced subscription the subscription `args` are used automatically for filtering messages, but when using advanced filtering it is necessary to specify it explicitly in the filter expression.
> Fix duplicates when starting multiple sessions for the same user

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/base.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/claude.py
- lib/model-interfaces/langchain/functions/request-handler/index.py
- lib/user-interface/react-app/package-lock.json
- lib/user-interface/react-app/package.json
- lib/user-interface/react-app/src/components/chatbot/chat-input-panel.tsx
- lib/user-interface/react-app/src/components/chatbot/chat-message.tsx
- lib/user-interface/react-app/src/components/chatbot/utils.ts
Resolves #391
In order to support the new Message API for Claude 3 models and given that this API is supported on all previous models, we choose to create a single Claude adapter that leverages it. 
- Instantiate the custom Bedrock Model Adapter instead of using the stock langchain one which does not support this API yet
- Implement the necessary changes to use the Message API
- Fixing some issues with the Chat React component and token sending 
> Feat message api

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/__init__.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/base.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/llama2_chat.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/mistral.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/shared/meta/llama2_chat.py
Resolves: #390 
Given that the prompt format of Mistral and Mixtral are identical to Llama2, we reused the Llama2 adapter registering it also for Mistral models
The input and output adaptations are different and taken care by the base Bedrock LLM class
Finally, we revised the LLama2 prompts.
> Add support for Mistral models via Bedrock

- cli/magic-config.ts
*Issue #345 *
* Added 3 additional questions (in CLI) to capture vpcid &  vpc endpoints details
* Validating vpc-id while capturing user input
> CLI option to specify existing VPC ID

- lib/chatbot-api/functions/outgoing-message-appsync/index.ts
When using streaming mode, single tokens are published to SQS and then processed by a lambda function in micro-batches of 10 items. 
Each message is then published as a mutation to AppSync and triggers a refresh of the UI. Tokens are reordered client side before the resulting text is displayed.
We have noticed that the text is often scrambled and upon each refresh it gets reordered. Upon investigation this is due to the fact that records in SQS batches are not in order and Lambda Powertools batch processor processes the records in the same order as they are received. This causes a lot of reordering client side since token are received individually.
Eg:
```
Batch: [friend!, Hello, my]
Client:
friend -> "friend!"
Client:
Hello -> "Hello …
```
> Improved streaming experience

- lib/user-interface/react-app/src/components/chatbot/chat-input-panel.tsx
Multimodal chat is trigger by the upload of an image in the input box, but on subsequent chats the normal text chat mode (langchain) would be if no new image is uploaded.
We now check if there are any images in the chat history, and if that is the case, we continue to use the `multimodal` chat mode.
> Continue to use multimodal mode in a chat using images

- lib/aws-genai-llm-chatbot-stack.ts
- lib/model-interfaces/idefics/index.ts
Resolves: #412
We configure the `RestApi` construct to add the necessary role automatically.
> Add setting for automatic creation of cloudwatch role on Api Gateway

- lib/user-interface/react-app/src/components/chatbot/chat-input-panel.tsx
To allow for multimodal models, like Claude 3, to be used both for multimodal chat and RAG we selected which interface to use based on the presence of images in the user input or in the chat history. 
This  logic does not work if the user starts a multimodal chat (using images) and then switches to a text-only model, since we would still route the input to the multimodal interface which does not recognize the selected model
We added a check to the existing conditions to verify that the selected model has IMAGE input modality support.
> Correctly switch interface based on chat history and model capabilities

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/claude.py
- lib/user-interface/react-app/src/components/chatbot/chat-input-panel.tsx
- improvement to the condense prompt used by Langchain for the claude models. The new prompt uses xml tags to identify sections of the prompt and be more consistent in generating correct asnwers
- fix at the interface selection logic with improved checks on when to trigger the multimodal interface
> Improved Claude prompts for Langchain and fix to interface selection

- cli/aws-cron-expressions.ts
- cli/aws-cron-validator.ts
- cli/magic-config.ts
- docs/documentation/sagemaker-schedule.md
- lib/models/index.ts
- lib/models/sagemaker-schedule.ts
- lib/shared/types.ts
- package-lock.json
- package.json
This change implements the ability to set a schedule via event bridge to toggle on and off the sagemaker hosted models. Typically the solution is consumed during business hours so enabling a schedule to suit those hours makes sense. See updated docs for more information.
I had to build a class to validate the peculiar cron expression format that Event Bridge supports to help give feedback to users inputting a cron expression early, rather than waiting for a deployment to fail later.
> feat: adding schedule option for sagemaker models

- cli/magic-config.ts
In the CLI some schedule options were being shown despite not being requested.
Despite a config option set to be skipped it still holds a default value with the select directive, this seems to be another issue with enquirer logic, have worked around it by adding a nested check for options that have the defaulted option.
> fix: logic bug in CLI

- docs/.vitepress/config.mts
Add missing link to new docs page on sagemaker schedule
> fix: missing link to schedule docs

- docs/.vitepress/config.mts
- docs/guide/prioritization.md
The PR adds documentation to cover how we prioritize feature development and changes. The goal of this document is to create more transparency around how efforts selected for development.
> docs: Added development prioritization document

- lib/shared/layers/python-sdk/python/genai_core/embeddings.py
Fixes the exceptions being thrown when using Cohere embedding models
Correctly set the `input_type` by using `Enum.value`
(see lines 108-110)
> Fixes Cohere embeddings

- lib/user-interface/react-app/README.md
Fixes #159 
Address the comments from @jtlz2
`npm run build:dev` only required to build the `aws-export.json` file from local variables. It must NOT be used when getting the configuration file from the deployment.
> fix(readme): clarifying how to run the interface locally

- lib/user-interface/react-app/src/app.tsx
- lib/user-interface/react-app/src/common/hooks/use-navigation-panel-state.ts
- lib/user-interface/react-app/src/components/base-app-layout.tsx
- lib/user-interface/react-app/src/components/chatbot/sessions.tsx
- lib/user-interface/react-app/src/components/navigation-panel.tsx
- lib/user-interface/react-app/src/pages/chatbot/models/models.tsx
- lib/user-interface/react-app/src/pages/chatbot/playground/multi-chat-playground.tsx
- lib/user-interface/react-app/src/pages/chatbot/playground/playground.tsx
- lib/user-interface/react-app/src/pages/chatbot/sessions/sessions.tsx
- lib/user-interface/react-app/src/pages/rag/cross-encoders/cross-encoders.tsx
- lib/user-interface/react-app/src/pages/rag/embeddings/embeddings.tsx
- lib/user-interface/react-app/src/pages/rag/semantic-search/semantic-search.tsx
- lib/user-interface/react-app/src/pages/rag/workspaces/workspaces.tsx
This change provides  better visibility to Session History feature, and conform with CloudScape design guidelines. 
It introduces information panels on most screens and implements a framework to easily add information panels throughout the application. 
> Session History screen

- docs/guide/deploy.md
- package.json
Instructions mentioned dependency on typescript 3.8+ but the code should install and use the right version of typescript (5+) already.
- updated `develop.md`
- replaced `tsc` with `npx tsc` to force the local version to be used in case the developer has a global version of typescript installed
> Improved development instructions

- .github/workflows/build.yaml
N/A
npm commands for build checks were just being ran in the repository root, and would skip over the user-interface/react-app directory, allowing errors to slip through the review process. This PR adds build checks for the UI and adds a cdk synth command to serve as a temporary measure until the preferred e2e testing for cdk is ready.
> Include UI in smoke-build GitHub action & add cdk synth check

- lib/shared/types.ts
EU-WEST-3 Paris and AP-SOUTHEAST-2 Sydney now supported by Bedrock
> feat: bedrock region expansion eu-west-3 & ap-southeast-2

- cli/magic-config.ts
- docs/documentation/model-requirements.md
- lib/models/index.ts
- lib/shared/types.ts
- package-lock.json
- package.json
#461 
As per issue, previously working Mistral models hosted via Sagemaker from HuggingFace are now broken and failing to start.
This is resolved by adding a feature to pass a now required HF_Token parameter to the model definition.
Required to update container runtimes for Mistral models to the latest that have proper support for HF_TOKEN. This also required bumping generative AI constructs to latest in order to be able to reference latest containers.
Have tested the changes and works as expected.
> fix: add ability to set HF_token now required by Mistral models on HF

- cli/magic-config.ts
#450 
ACM cert and domain name entries are required when selecting private website or when creating a public website with a custom domain. this change adds validation to those fields to make them required in those circumstances and does some additional validation to ensure a valid ACM ARN is supplied.
> fix: logic for private website and add validation on config params

- lib/user-interface/react-app/src/components/chatbot/chat-message.tsx
Some documents (eg text docs) returned by RAG do not provide a `path` field in the metadata making the UI crash. 
added fallback rules for the document tab labels
> fix(chat message): added fallback rules for the document tab labels

- lib/user-interface/react-app/src/pages/rag/add-data/data-file-upload.tsx
*Issue #452 *
*Description of changes:* Added validation so that filenames having comma cannot be uploaded. We are using comma as a separator later in the code and hence the upload fails if the file name has comma in it. This validation will ensure that filenames having comma are not allowed to be uploaded.
> fix: Added validation for filenames having comma

- lib/shared/layers/python-sdk/python/genai_core/documents.py
Previously an error in logic always resulted in only a single page crawl ignoring links and limit set in GUI always defaulting to 1 as urls_to_crawl only contains multiple values when sitemap option is used. Now limit works correctly in both modes.
> fix: website crawler limited to only 1 page crawl

- cli/magic-config.ts
just a small logic fix to only show adding kendra existing index, if kendra rag enabled
> fix: cli only show kendra existing index if kendra rag enabled

- lib/chatbot-api/functions/api-handler/routes/documents.py
UI not able to list Document in workspace for example, with Console log : 
"Field required [type=missing, "    for ListDocumentsRequest
Is related to pydantic parser validation from lambda powertools
https://docs.powertools.aws.dev/lambda/python/latest/utilities/parser/
Optionnal Type is not sufficient, we need to initialize Optional fields to None
> fix: Added None value for pydantic validation

- bin/config.ts
- lib/model-interfaces/idefics/index.ts
- lib/shared/types.ts
Hi,
since release version 4.0.3 it seems there is condition disappeared for Idefics Interface activation or not.
You can compare this latest version with previous one like v4.0.3 at the same line :
[aws-genai-llm-chatbot/lib/aws-genai-llm-chatbot-stack.ts](https://github.com/aws-samples/aws-genai-llm-chatbot/blob/3c710bf28bd74eb3b576b863a4b678ed8ef06e0b/lib/aws-genai-llm-chatbot-stack.ts#L110)
Line 110 in [3c710bf](https://github.com/aws-samples/aws-genai-llm-chatbot/commit/3c710bf28bd74eb3b576b863a4b678ed8ef06e0b)
is it normal or a mistake ? In my case I cannot not deploy anymore due this new resource not available before and it need a default security group ID for private VPC endpoint.
This happened when VPC already exist, it seems the method "ec2.Vpc.fromLookup" does not detect a …
> Dealing with existant VPC for IdeficsInterface deployment

- lib/model-interfaces/idefics/index.ts
closes #493 
The VPC lookup does not lookup the default security group. So using the `default` name searches the security group.
> fix: lookup default sg when using existing vpc

- lib/shared/index.ts
*Description of changes:* Created Bedrock endpoint incase of private deployment as the bedrock endpoint helps to list the models. The models timesout if the VPC endpoint doesnt exist
> Added code to create bedrock vpc endpoint for bedrock as the models list endpoints timesout

- cli/magic-config.ts
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/ai21_j2.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/base.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/claude.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/cohere.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/llama2_chat.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/llama3.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/mistral.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/titan.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/sagemaker/meta/llama2_chat.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/sagemaker/mistralai/mistral_instruct.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/sagemaker/mistralai/mixtral_instruct.py
- lib/model-interfaces/langchain/index.ts
- lib/shared/layers/common/requirements.txt
- lib/shared/shared-asset-bundler.ts
- lib/shared/types.ts
- package-lock.json
This PR adds supports for Bedrock Guardrails to the Chatbot. You create a Guardrail outside of the chatbot (eg via console, CloudFormation, CDK) and then you add the Guardrail Identifier and Version when configuring the chatbot.
With this PR we have also restructured the config command, moving all advanced configuration options at the end and making them optional.
> Adding Bedrock Guardrails support

- lib/chatbot-api/functions/api-handler/routes/documents.py
When attempting to view details of an RSS feed, the getDocument endpoint was throwing an error around crawler_properties, potentially due to a merge in the past. The updated code properly handles if crawler properties are applied. 
> fix(api): Fixed getDocument(s) endpoint errors

- docs/.vitepress/config.mts
- docs/documentation/aws-resources-deployed.md
This document section aims to provide an overview of majority of the AWS Resources deployed. As customers are looking to understand the security requirements associated with not only running it, but getting it deployed in a secure environment, understanding at a high level what resources may be created in the AWS Account can be helpful insight. 
The doc is best effort coverage. It does not include IAM permissions between resources, etc. 
> docs: Add AWS Resources Overview to documentation site

- lib/user-interface/react-app/src/components/chatbot/chat-input-panel.tsx
- lib/user-interface/react-app/src/components/chatbot/chat-message.tsx
- lib/user-interface/react-app/src/components/chatbot/multi-chat.tsx
- lib/user-interface/react-app/src/components/chatbot/utils.ts
#501
Fixes two issues:
* Only shows a token if the previous ones are available (so it only adds the words at the end)
* Fix token missed. This happens when receiving 2 tokens in parallel. The fix is to move the reference of `lastMessage.tokens` out of `updateMessageHistoryRef` (so it uses the same array)
https://github.com/user-attachments/assets/4e4b5a6b-a67d-40a0-9d88-8181244b541b
> fix: Token order during streaming

- cli/magic-config.ts
Hint date format was incorrect. (event bridge expects the date with dashes)
> bug: Fix CLI schedule hint

- lib/shared/alpine-zip/Dockerfile
- lib/shared/web-crawler-dockerfile
Replace docker base image location to use Amazon Public ECR to prevent docker hub throttling when the build is running in an AWS account.
Images
https://gallery.ecr.aws/docker/library/python
https://gallery.ecr.aws/docker/library/alpine
> chore: Get base docker image from Public ECR

- lib/layer/index.ts
- lib/shared/shared-asset-bundler.ts
- pytest_requirements.txt
Reducing the layer size reduces the init time. (5s ->3.5s)
To reduce the layer size
- Remove boto 3 and use the one available in the runtime
- Remove SQL Alchemy which is only needed when using SQL based memory in langchain.
- Remove `pyc` files
The large package part of this project is `numpy` needed by `langchain`. A future improvement could be to try to reduce its size.
Another improvement could be to increase the memory(and cpu). 512->1024 would reduce it further by  ~0.3s
*Testing*
Ran integration tests
> feat: Reduce layer size to reduce cold start

- lib/user-interface/react-app/src/components/chatbot/chat-input-panel.tsx
- lib/user-interface/react-app/src/components/chatbot/chat.tsx
The useEffect fetching the models & workspace is called multiple times. It should be running once. 
> bug: Fix unnecessary calls (Chat-input-panel)

- lib/model-interfaces/langchain/functions/request-handler/adapters/azureopenai/azuregpt.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/openai/gpt.py
- lib/shared/file-import-batch-job/requirements.txt
- lib/shared/layers/common/requirements.txt
- lib/shared/layers/python-sdk/python/genai_core/embeddings.py
- lib/shared/layers/python-sdk/python/genai_core/models.py
#572
The langchain classes in the community package are deprecated and causing issues (see issue #572)
Upgrading the library to use `langchain-openai` as defined in [the doc](https://python.langchain.com/v0.2/docs/integrations/platforms/openai/#installation-and-setup)
> bug: Upgrade openai library following the langchain upgrade.

- docs/documentation/monitoring.md
- lib/rag-engines/aurora-pgvector/index.ts
- tests/chatbot-api/__snapshots__/chatbot-api-construct.test.ts.snap
* Proofread the new documentation page.
* Revert `StorageEncrypted` change. Setting it  is causing cloudformation to re-create the cluster.
> fix: documentation wording + revert a change causing Aurora re-creation

- cli/magic-config.ts
- lib/aws-genai-llm-chatbot-stack.ts
- lib/chatbot-api/index.ts
- lib/shared/index.ts
- lib/shared/types.ts
- lib/user-interface/index.ts
- lib/user-interface/public-website.ts
- lib/user-interface/react-app/index.html
- lib/user-interface/react-app/src/common/utils.ts
- lib/user-interface/react-app/vite.config.ts
- tests/__snapshots__/cdk-app.test.ts.snap
- tests/chatbot-api/__snapshots__/chatbot-api-construct.test.ts.snap
* Upgrade the cloudfront CDK Construct. `CloudFrontWebDistribution` is deprecated
* Add [Security headers](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-responseheaderspolicy-securityheadersconfig.html)
* Added WAF to throttled the Appsync request per IP. Added one rule specific for `sendQuery`
*Testing*
* Verified throttling from both cloudfront and appsync by call many time the LLM
* Verified the front end still works with federation, image upload. The content `ContentSecurityPolicy` header is strict to prevent using unexpected resources.
> feat: Added rate limit + security headers.

- lib/user-interface/public-website.ts
Partial Revert of  #581  due to #585 
The construct `CfnWebACL` when associated with Cloudfront has to be deployed in us-east-1.
*Testing*
Deployed in a second region
> revert: Remove Cloudfront WAF due to deployment in incorrect region.

- lib/chatbot-api/index.ts
- tests/__snapshots__/cdk-app.test.ts.snap
- tests/chatbot-api/__snapshots__/chatbot-api-construct.test.ts.snap
The internal calls sending chunks (LLM Response Streaming) to the end user was reaching the WAF throttling limit added in #581.
To prevent this, the change excludes the VPC IPs from the throttling limit.
*Testing*
Check WAF Metrics + requested large output from the model with streaming.
> bug: Exclude internal calls from WAF rate limiter

- cli/magic-config.ts
*Issue #, if available:* #592
Fixes the following:
* When RAG is disabled, the script should not try to set a default embedding model since there are none. (It was causing the failure in the issue above)
* Updated the wording `enableSagemakerModels` since it refers to only text generation models at this time.
* Fixed `defaultEmbedding` check. It should show a warning if a SageMaker embedding model is selected but none is available.
* Fixed BedRock KB always enabled (even when there is none)
* Fixed asking for a Kendra external index when it's disabled.
> bug: Fix cli script when RAG is not enabled

- cli/magic-config.ts
*Issue #, if available:* #592
The cli library `enquirer` silently exits when the question is skipped and invalid. Added a check.
> bug: Fix cli stopping when using Bedrock KB

- lib/aws-genai-llm-chatbot-stack.ts
- lib/chatbot-api/functions/api-handler/routes/workspaces.py
- lib/monitoring/index.ts
- tests/monitoring/__snapshots__/monitoring-contruct.test.ts.snap
- tests/monitoring/monitoring-contruct.test.ts
Follow up of #598. The Opensearch input validation was incorrect.
In addition added a missing use of the shared CMK (Alarm topic)
> bug: Fix incorrect input validation (OpenSearch following Pydantic up date) + Added missing CMK use (Alarm topic)

- .github/workflows/e2e-validation.yml
- integtests/chatbot-api/aurora_workspace_test.py
- lib/model-interfaces/idefics/functions/request-handler/adapters/base.py
- lib/model-interfaces/idefics/functions/request-handler/adapters/nova.py
- lib/user-interface/react-app/package-lock.json
- lib/user-interface/react-app/src/components/chatbot/chat-message.tsx
- package-lock.json
Trigger validation on changes on the main branch.
> feat: Main branch validation

- cli/magic-config.ts
- lib/chatbot-api/application-dynamodb-tables/index.ts
- lib/chatbot-api/chatbot-dynamodb-tables/index.ts
- lib/chatbot-api/index.ts
- lib/rag-engines/index.ts
- lib/rag-engines/rag-dynamodb-tables/index.ts
- lib/shared/index.ts
- lib/shared/types.ts
- lib/user-interface/react-app/package-lock.json
- lib/user-interface/react-app/package.json
- lib/user-interface/react-app/src/components/chatbot/chat-input-panel.tsx
- lib/user-interface/react-app/src/components/chatbot/file-dialog.tsx
- lib/user-interface/react-app/src/components/chatbot/multi-chat-input-panel.tsx
- lib/user-interface/react-app/src/components/chatbot/multi-chat.tsx
- package-lock.json
- package.json
- pytest_requirements.txt
- tests/__snapshots__/cdk-app.test.ts.snap
- tests/chatbot-api/__snapshots__/chatbot-api-construct.test.ts.snap
- tests/monitoring/__snapshots__/monitoring-contruct.test.ts.snap
- feat:
- Add DynamoDB delete protection to config
- chores:
- Bump `esbuild` version to `0.25.0`
- Bump pyopenssl version to `24.3.0` 
> feat: Add configurable ddb delete protection

- lib/user-interface/react-app/package-lock.json
- lib/user-interface/react-app/package.json
- package-lock.json
This PR updates the vite package to fix the moderate security vulnerability (GHSA-859w-5945-r5v3) related to server.fs.deny being bypassed with /. for files under project root.
> fix: update vite to fix security vulnerability

- aws-genai-llm-chatbot/modules/chatbot/deployspec.yaml
- lib/aws-genai-llm-chatbot-stack.ts
- lib/user-interface/index.ts
- lib/user-interface/private-website.ts
- tests/__snapshots__/cdk-app.test.ts.snap
Add a new CfnOutput with metadata containing key information about the deployed resources, including:
- User interface domain name and CloudFront distribution
- Cognito user pool details
- GraphQL API information
- API keys secret name
- Load balancer DNS for private website deployments
Update deployspec.yaml to extract the metadata using jq from the specific stack output. Expose the privateWebsite and loadBalancer properties to make them accessible for the metadata output.
> feat(metadata): Add metadata output for Nexus integration

- lib/authentication/index.ts
- tests/__snapshots__/cdk-app.test.ts.snap
- tests/authentication/__snapshots__/autentication-construct.test.ts.snap
- tests/chatbot-api/__snapshots__/chatbot-api-construct.test.ts.snap
on starting application with user having role workspace_manager, no UI is loaded. 
in application codeline, the checks were done for workspace-manager instead of workspace_manager. Changed it for consistency.
> fix(auth): enforce workspace manager access control

- lib/authentication/index.ts
- lib/authentication/lambda/addFederatedUserToUserGroup/index.py
This PR updates the Cognito authentication flow for federated users by replacing the POST_AUTHENTICATION trigger with PRE_SIGN_UP and POST_CONFIRMATION triggers. This change resolves the issue where users were experiencing 404 errors after logout when using Cognito federation.
When using Cognito federation, the previous implementation relied on the POST_AUTHENTICATION trigger to assign users to groups. However, this approach caused issues where users would get 404 errors after logout, and the Lambda function would only trigger after the user had already logged into the console.
The solution implements a more robust authentication flow by:
1. Using PRE_SIGN_UP trigger to validate and prepare for group assignment before the user is created
2. Using POST_CONFIRMATION trigger to assign the …
> Bug Fix: Update Cognito Authentication Flow
