aws-samples/aws-genai-llm-chatbot

- lib/aws-genai-llm-chatbot-stack.ts
- lib/model-interfaces/langchain/index.ts
- lib/rag-sources/aurora-pgvector/document-indexing.ts
- lib/rag-sources/aurora-pgvector/functions/document-indexing/Dockerfile
- lib/rag-sources/aurora-pgvector/functions/semantic-search-api/Dockerfile
- lib/rag-sources/aurora-pgvector/functions/vectordb-setup/Dockerfile
- lib/rag-sources/aurora-pgvector/index.ts
- lib/rag-sources/opensearch-vectorsearch/functions/index-document/Dockerfile
- lib/sagemaker-model/hf-custom-script-model/index.ts
- lib/user-interface/index.ts
> Move to X86_64 architecture

- package-lock.json
- package.json
Removed unnecessary type definitions
> fix: removed unnecessary type defs

- tsconfig.json
> fix: ignore react app folder for tsc

- .gitignore
- lib/model-interfaces/langchain/functions/request-handler/adapters/base/base.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/claude.py
52
Replaces Bedrock client with BedrockChat client for Claude
> Fix Anthropic prompt - second take

- bin/config.ts
- cli/magic-create.ts
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/titan.py
> Feat: adding the new Titan Embeddings model

- README.md
- cli/magic-create.ts
> Kendra createIndex option

- cli/magic-create.ts
#65 
The current code was creating an extra level in the configuration dictionary. The fix correctly creates the configuration file.
> fix: correct creation of config.json

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/cohere.py
- lib/shared/layers/common/requirements.txt
* bump langchain version to include https://github.com/langchain-ai/langchain/pull/11230 
* fix typo in Bedrock Cohere params
> Bedrock Cohere support fixes

- lib/chatbot-api/rest-api.ts
- lib/model-interfaces/langchain/index.ts
Allow to access local Kendra Indexs without roleArn
> Allow to access local Kendra Indexs without role

- cli/magic-create.ts
Added support to external kendra indexes in the create wizard
> fix: support for external kendra indexes

- lib/chatbot-api/functions/api-handler/routes/documents.py
- lib/chatbot-api/functions/api-handler/routes/workspaces.py
- lib/chatbot-api/rest-api.ts
- lib/rag-engines/data-import/functions/website-crawling-workflow/website-parser/index.py
- lib/rag-engines/index.ts
- lib/rag-engines/workspaces/delete-workspace.ts
- lib/rag-engines/workspaces/delete-wrokspace.ts
- lib/rag-engines/workspaces/functions/delete-workspace-workflow/delete/index.py
- lib/rag-engines/workspaces/index.ts
- lib/shared/layers/python-sdk/python/genai_core/aurora/delete.py
- lib/shared/layers/python-sdk/python/genai_core/chunks.py
- lib/shared/layers/python-sdk/python/genai_core/documents.py
- lib/shared/layers/python-sdk/python/genai_core/kendra/delete.py
- lib/shared/layers/python-sdk/python/genai_core/opensearch/delete.py
- lib/shared/layers/python-sdk/python/genai_core/utils/delete_files_with_prefix.py
- lib/shared/layers/python-sdk/python/genai_core/websites/crawler.py
- lib/shared/layers/python-sdk/python/genai_core/workspaces.py
- lib/user-interface/react-app/src/common/api-client/workspaces-client.ts
- lib/user-interface/react-app/src/common/constants.ts
- lib/user-interface/react-app/src/components/rag/workspace-delete-modal.tsx
- lib/user-interface/react-app/src/pages/rag/add-data/crawl-website.tsx
- lib/user-interface/react-app/src/pages/rag/workspaces/workspaces-page-header.tsx
> Workspace deletion

- lib/chatbot-api/functions/api-handler/index.py
- lib/chatbot-api/functions/api-handler/routes/kendra.py
- lib/chatbot-api/functions/api-handler/routes/rag.py
- lib/chatbot-api/functions/api-handler/routes/workspaces.py
- lib/shared/layers/python-sdk/python/genai_core/aurora/query.py
- lib/shared/layers/python-sdk/python/genai_core/kendra/data_sync.py
- lib/shared/layers/python-sdk/python/genai_core/kendra/query.py
- lib/shared/layers/python-sdk/python/genai_core/opensearch/query.py
- lib/shared/layers/python-sdk/python/genai_core/workspaces.py
- lib/user-interface/react-app/src/common/api-client/api-client.ts
- lib/user-interface/react-app/src/common/api-client/kendra-client.ts
- lib/user-interface/react-app/src/common/api-client/rag-engines-client.ts
- lib/user-interface/react-app/src/common/api-client/workspaces-client.ts
- lib/user-interface/react-app/src/common/types.ts
- lib/user-interface/react-app/src/pages/rag/create-workspace/create-workspace-kendra.tsx
- lib/user-interface/react-app/src/pages/rag/create-workspace/kendra-form.tsx
- lib/user-interface/react-app/src/pages/rag/workspace/kendra-workspace-settings.tsx
- lib/user-interface/react-app/src/pages/rag/workspaces/workspaces-page-header.tsx
> Kendra Index fixes

- lib/user-interface/react-app/src/pages/rag/embeddings/metrics-matrix.tsx
Fix #111 
Corrected the display of the matrix
> fix: correct number of columns in matrix

- cli/magic-create.ts
fix #136 
Added filter to only include models that are available in current configuration
> fix: select models that are available in current version

- cli/magic-create.ts
- package.json
fix #136 
Added safety guards in case of missing config
> fix: safety guards in case of missing config

- lib/chatbot-api/functions/api-handler/routes/documents.py
*Issue #143
Typo error with allowed extensions for document api handler.
> fix: replace csv by .csv

- bin/config.ts
- lib/aws-genai-llm-chatbot-stack.ts
- lib/chatbot-api/functions/api-handler/routes/cross_encoders.py
- lib/chatbot-api/functions/api-handler/routes/embeddings.py
- lib/chatbot-api/rest-api.ts
- lib/model-interfaces/langchain/index.ts
- lib/rag-engines/data-import/file-import-batch-job.ts
- lib/rag-engines/data-import/index.ts
- lib/rag-engines/index.ts
- lib/shared/layers/python-sdk/python/genai_core/cross_encoder.py
- lib/shared/layers/python-sdk/python/genai_core/embeddings.py
- lib/user-interface/index.ts
- lib/user-interface/react-app/src/common/types.ts
- lib/user-interface/react-app/src/components/navigation-panel.tsx
- lib/user-interface/react-app/src/pages/rag/cross-encoders/cross-encoders.tsx
Allow to deploy Kendra without SageMaker endpoints
> Allow to deploy Kendra without SageMaker endpoints

- lib/user-interface/react-app/src/common/constants.ts
- lib/user-interface/react-app/src/components/app-configured.tsx
- lib/user-interface/react-app/src/components/chatbot/chat.tsx
- lib/user-interface/react-app/src/components/global-header.tsx
- lib/user-interface/react-app/src/components/navigation-panel.tsx
- lib/user-interface/react-app/src/pages/chatbot/models/models.tsx
- lib/user-interface/react-app/src/pages/not-found.tsx
- lib/user-interface/react-app/src/pages/rag/add-data/add-data.tsx
- lib/user-interface/react-app/src/pages/rag/create-workspace/create-workspace.tsx
- lib/user-interface/react-app/src/pages/rag/cross-encoders/cross-encoders.tsx
- lib/user-interface/react-app/src/pages/rag/dashboard/dashboard.tsx
- lib/user-interface/react-app/src/pages/rag/embeddings/embeddings.tsx
- lib/user-interface/react-app/src/pages/rag/engines/engines.tsx
- lib/user-interface/react-app/src/pages/rag/semantic-search/semantic-search.tsx
- lib/user-interface/react-app/src/pages/rag/workspace/workspace.tsx
- lib/user-interface/react-app/src/pages/rag/workspaces/workspaces.tsx
- lib/user-interface/react-app/src/pages/welcome.tsx
*Description of changes:* Currently the chatbot name is hardcoded in different files. If someone wants to change the name, changes are required in a lot of files.
Used a constant for the chatbot name. It would make easier to change the name by making changes in a single file.
> Used a constant for the chatbot name.

- lib/shared/layers/common/requirements.txt
- Bump langchain version to `0.0.331`
> Bump langchain version  to 0.0.331

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/cohere.py
resolves #234 
Modified adapter Regexp to also match `light-text`
> feat(cohere_command_light): support for command light

- lib/user-interface/react-app/src/components/chatbot/types.ts
Fixing a missing type that blocks building the UI
> fix(llm_prompts): missing type

- lib/user-interface/react-app/src/common/helpers/embeddings-model-helper.ts
- lib/user-interface/react-app/src/pages/rag/create-workspace/create-workspace-aurora.tsx
- lib/user-interface/react-app/src/pages/rag/workspace/aurora-workspace-settings.tsx
- lib/user-interface/react-app/src/pages/rag/workspace/open-search-workspace-settings.tsx
Update the typo for "Dimensions" in workspaces
> Fixit dimension spelling

- README.md
N/A
After meeting with solutions architect I add this pro-tips for every one
> Add section to manage non english kendra index

- lib/shared/layers/python-sdk/python/genai_core/upload.py
fix: #264
normalize the file name encoding using the NFC standard
for more info about unicode character representation standards check https://en.wikipedia.org/wiki/Unicode_equivalence
> fix(file import):  encode file names in NFC format

- lib/model-interfaces/langchain/functions/request-handler/adapters/sagemaker/mistralai/__init__.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/sagemaker/mistralai/mixtral_instruct.py
- lib/models/index.ts
- lib/sagemaker-model/container-images.ts
- lib/shared/types.ts
*Issue #, if available:* 
#312
Adding support for Mixtral instruct 0.1 and Mistral instruct 0.2
added updated container image references which are required to support the newer models
tested the changes
> feat: adding support for mixtral 0.1 and mistral instruct 0.2

- lib/user-interface/react-app/src/pages/rag/semantic-search/semantic-search.tsx
Fix #327 
Added checks in the UI for the result items being `null` in addition to checking for any items being returned
> fix(ui): improved checking on the results returned by Semantic Search API

- lib/user-interface/react-app/schema.json
- lib/user-interface/react-app/src/API.ts
- lib/user-interface/react-app/src/graphql/mutations.ts
- lib/user-interface/react-app/src/graphql/queries.ts
Update to the autogenerated client files for interacting with the graphql backend.
Used `amplify codegen` in the lib/user-interface/react-app folder.
Configured via `amplify codegen configure`
Manually added the AppSync appId in the `.graphqlconfig.yml` file
> Update of autogenerated graphql client files

- lib/aws-genai-llm-chatbot-stack.ts
Fix error with nag suppression path not found if Kendra external index is enabled
> fix: do not suppress Kendra default policy unless createIndex is chosen

- lib/model-interfaces/langchain/README.md
Extra note on customizing the prompt when RAG is used/enabled.
> Update README.md for additional models support

- cli/magic-create.ts
Fixing few issues that have been introduced in the create command:
- remove extra `console.log`
- reordered option for enabling Kendra enterprise edition
> fix(magic create): removed console.log and reordered options

- lib/aws-genai-llm-chatbot-stack.ts
*Issue #, if available:* #344
cdk-nag suppressions are dynamically created based on the number of available AZs
> Fix #344. Dynamically create cdk-nag suppression based on AZ number

- lib/user-interface/react-app/src/components/chatbot/utils.ts
Workaround for #341
Workaround to avoid duplicate messages polluting the client code and the UI. This does not currently solve the underlying problem of why duplicate messages are received.
A proper fix will come later. Stopgap solution.
> fix(duplicates): workaround for duplicates appearing in the UI

- lib/user-interface/react-app/src/common/api-client/api-client.ts
Fix #372 
Removed argument from constructor call
> fix(#372): remove constructor args

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/mistral.py
Fix for changes introduced by #396
> Update of registry location in Mistral adapter

- lib/aws-genai-llm-chatbot-stack.ts
Resolves: #402 
remove length > 0 condition for idefics path suppressions so they are always suppressed
> fix: remove length > 0 condition for idefics path suppressions

- lib/model-interfaces/idefics/functions/request-handler/adapters/claude.py
> fix(claude multimodal): key error

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/mistral.py
Added specific mapping for `max_tokens` for Mistral models which differ from LLama2
> Correct paramter mapping for Mistral models

- bin/config.ts
- cli/magic-config.ts
- docs/.vitepress/config.mts
- docs/documentation/cf-geo-restriction.md
- lib/shared/types.ts
- lib/user-interface/public-website.ts
- package-lock.json
- package.json
This adds a feature which allows users to set a country based allow list to their CF distribution.
> feat: allow users to apply a country restriction with CF

- docs/documentation/model-requirements.md
- lib/model-interfaces/langchain/functions/request-handler/adapters/__init__.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/azureopenai/__init__.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/azureopenai/azuregpt.py
- lib/shared/layers/python-sdk/python/genai_core/models.py
- lib/shared/layers/python-sdk/python/genai_core/types.py
*Issue #380 : Azure OpenAI integration*
Integrate Azure OpenAI model as ThirdParty
> Integration of Azure OpenAI models as third party

- lib/shared/layers/python-sdk/python/genai_core/user_feedback.py
- lib/user-interface/react-app/src/components/chatbot/chat.tsx
- lib/user-interface/react-app/src/components/chatbot/multi-chat.tsx
*Issue #374 *
*Description of changes:* added full prompt capture to feedback to address #374 
> Added Full Prompt to Feedback

- lib/user-interface/react-app/src/components/chatbot/sessions.tsx
Fix #435
Correct warning ignore statement
> fix(no unused var): correct ignore

- scripts/cloud9-resize.sh
* Added support for IMDSv2 tokens
* Changed the default filesystem type for AL2023
> Cloud9-resize.sh supports Cloud9 instances based on AL2023

- docs/guide/deploy.md
> Improvements to the deploy documentation

- scripts/cloud9-resize.sh
Now it's possible to run script like this: ./cloud9-resize.sh 1 120
> Ability to run cloud9-resize.sh in non-interactive mode

- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/__init__.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/llama3.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/shared/meta/__init__.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/shared/meta/llama3_instruct.py
Adding Llama3 adapter using the right template format based on https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/#special-tokens-used-with-meta-llama-3
> Llama3 adapter

- lib/shared/layers/python-sdk/python/genai_core/models.py
- lib/shared/layers/python-sdk/python/genai_core/types.py
> Spell correctly ENUM type value

- lib/model-interfaces/langchain/README.md
- lib/model-interfaces/langchain/functions/request-handler/adapters/azureopenai/azuregpt.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/ai21_j2.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/claude.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/cohere.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/llama2_chat.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/bedrock/titan.py
- lib/model-interfaces/langchain/functions/request-handler/adapters/openai/gpt.py
- lib/shared/layers/common/requirements.txt
Resolves #397 
- Bumped langchain version to the latest version
- Moved imports to langchain_community when necessary
> Update to use langchain-community

- lib/rag-engines/kendra-retrieval/index.ts
- lib/shared/shared-asset-bundler.ts
Some resources had inconsistent naming making harder to understand resource dependencies
- change resource name
- removed unnecessary logging found while investigating the other issue
> Fix resource naming

- lib/aws-genai-llm-chatbot-stack.ts
*Issue #, if available:* #491
*Description of changes:* Fix nag suppression path that prevents deployment with Amazon Kendra workspace enabled.
> Fix #491 Amazon Kendra deployment

- lib/user-interface/index.ts
*Issue #514*
Modified the OAUTH redirectSignIn URL to include /index.html after the main domain. 
> Fix authentication with Cognito Federation in private deployment

- docs/guide/deploy.md
- integtests/chatbot-api/session_test.py
- integtests/clients/appsync_client.py
- integtests/clients/cognito_client.py
- integtests/conftest.py
- integtests/security/unauthorized_tet.py
- pytest_requirements.txt
Added backend integration tests which does the following
- Create a cognito user
- Create create sessions by calling the llm
- Fetch them and delete them.
> test: Added session integration tests

- tsconfig.json
Add `dist`to the list of ignored path for tsc to avoid recursive builds
> Ignore files in `dist` folder

- lib/shared/layers/python-sdk/python/genai_core/workspaces.py
Fix open search workspace creation (was throwing Type error)
> fix: Fix workspace creation (type error)

- integtests/conftest.py
Added support for Headless integration tests (Used to run Selenium UI Tests in an environment without a screen)
> test: Add Headless option

- integtests/chatbot-api/kendra_workspace_test.py
- integtests/chatbot-api/sagemaker_session_test.py
- integtests/chatbot-api/session_test.py
Some of the integration test were randomly failing.
* Do not ask for personal information (a name). Mistral sometimes prefers not to respond (use a plant color instead)
* Rework wait in Kendra tests 
* Use workspace specific data in Kendra test.
> test: Update/Fix integration tests.

- README.md
- lib/shared/file-import-batch-job/requirements.txt
- lib/shared/layers/common/requirements.txt
- lib/shared/web-crawler-batch-job/requirements.txt
Add a notice mentioning the use of LPGL and BlueOak
> chore: Add license notice.

- docs/guide/deploy.md
Update Cloud9 setup instruction to clone repo prior to resizing the volume
*Issue #, if available:* NA
*Description of changes:* Update deploy instructions for Cloud9 environment
> Update Cloud9 setup instruction

- lib/user-interface/react-app/src/components/chatbot/chat-message.tsx
- Reintroducing the copy button for AI text output which was accidentally removed in #613 
> Reintroduce copy button for AI text output

- .github/workflows/deploy.yml
> fix: deployment issues
